version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
    depends_on:
      - mariadb

  mailhog:
    depends_on:
      - mariadb
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
