version: '3.6'

services:
  mariadb:
    image: mariadb:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    volumes: .:/var/www/html
    ports:
      - 8080:80 
    depends_on:
      - mariadb

  mailhog:
    depends_on:
      - mariadb
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  php:
    image: php:7-apache
    volumes: .:/var/www/html
    ports:
      - 8000:80
